import { CollectibleType } from "@/app/api/interfaces/collectible";

export const allAnimalEmojis = [
  { icon: "🐌", label: "snail", type: CollectibleType.ANIMALS },
  { icon: "🐙", label: "octopus", type: CollectibleType.ANIMALS },
  { icon: "🐛", label: "caterpillar", type: CollectibleType.ANIMALS },
  { icon: "🐝", label: "bee", type: CollectibleType.ANIMALS },
  { icon: "🐞", label: "ladybug", type: CollectibleType.ANIMALS },
  { icon: "🐡", label: "blowfish", type: CollectibleType.ANIMALS },
  { icon: "🐢", label: "turtle", type: CollectibleType.ANIMALS },
  { icon: "🐨", label: "koala", type: CollectibleType.ANIMALS },
  { icon: "🐭", label: "mouse", type: CollectibleType.ANIMALS },
  { icon: "🐮", label: "cow", type: CollectibleType.ANIMALS },
  { icon: "🐯", label: "tiger", type: CollectibleType.ANIMALS },
  { icon: "🐰", label: "rabbit", type: CollectibleType.ANIMALS },
  { icon: "🐱", label: "cat", type: CollectibleType.ANIMALS },
  { icon: "🐳", label: "whale", type: CollectibleType.ANIMALS },
  { icon: "🐵", label: "monkey", type: CollectibleType.ANIMALS },
  { icon: "🐶", label: "dog", type: CollectibleType.ANIMALS },
  { icon: "🐷", label: "pig", type: CollectibleType.ANIMALS },
  { icon: "🐸", label: "frog", type: CollectibleType.ANIMALS },
  { icon: "🐹", label: "hamster", type: CollectibleType.ANIMALS },
  { icon: "🐻", label: "bear", type: CollectibleType.ANIMALS },
  { icon: "🐻‍❄️", label: "polar bear", type: CollectibleType.ANIMALS },
  { icon: "🐼", label: "panda", type: CollectibleType.ANIMALS },
  { icon: "🦀", label: "crab", type: CollectibleType.ANIMALS },
  { icon: "🦁", label: "lion", type: CollectibleType.ANIMALS },
  { icon: "🦊", label: "fox", type: CollectibleType.ANIMALS },
  { icon: "🦞", label: "lobster", type: CollectibleType.ANIMALS },
  { icon: "🦭", label: "seal", type: CollectibleType.ANIMALS },
  { icon: "🪲", label: "beetle", type: CollectibleType.ANIMALS },
];
